### ISSUE TITLE
Few intents are not responding

### ISSUE THREAD

**Issue by LKiera** [scalableminds/chatroom#113]
Hello there,
I have successfully connected rasa bot with chatroom and am getting response for most of it. Until now I just observed that few intents are not responding, and while printing the response on rasa action server, they respond fine. 
While using a debugger, something like this popped up:
`Unhandled promise rejection Error: "Could not parse message from Bot or empty message"`

Can anyone help me. Please?

Thank you

**Comment by hotzenklotz** [comment]
Hi. Please share the templates / code used for these responses. Perhaps they are somewhat mis-formatted or otherwise not supported by the chatroom yet. Thanks.

Perhaps related #112 ?

**Comment by LKiera** [comment]
`
class ActionNewsletter(Action):
    def name(self):
        return 'action_newsletter'
    def run(self, dispatcher, tracker, domain):
        response = api_to_text(api_str+"Newsletter")
        res = tracker.latest_message
        text = res['text']
        if (res['intent']['confidence'] < 0.1):
            response = spellcheck(text)
        if (response == None or response == ""):
            response = default_response
        dispatcher.utter_message(response)
class ActionCrmReports(Action):
    def name(self):
        return 'action_crm_reports'
    def run(self, dispatcher, tracker, domain):
        response = api_to_text(api_str+"Crm Reports")
        print (response)
        res = tracker.latest_message
        text = res['text']
        if (res['intent']['confidence'] < 0.1):
            response = spellcheck(text)
        if (response == None or response == ""):
            response = default_response
        dispatcher.utter_message(response)`

Newsletter works, where as crm reports doesn't

**Comment by hotzenklotz** [comment]
@LKiera The error message `Could not parse message from Bot or empty message` indicates that the JSON message send from the bot to the chatroom over the rest interface was ill formatted / unsupported. E.g. the message JSON must include a `text` attribute or `image` attribute. See the parsing method here: https://github.com/scalableminds/chatroom/blob/86eda9871800c912afa941d9e78335068eb5f472/src/ConnectedChatroom.js#L134

The Rasa REST channel should take care of these conversions automatically. From you could snippet above, I can not see any immediate problems. Here are some ideas to narrow the problem down.

- Check the browser's dev tools network tab to see the REST communication between bot server and chatroom. Verify that the bot response is indeed empty.
- Can you verify that `response` is always a string? Perhaps add an  `assert` statement. I am not sure what dispatcher.utter_message(...)` does with non-strings.
- Does the response contain any non-standard characters that might break something on JSON serialization?
- Make sure to run/execute your bot with `--verbose` on the command line to see maximum outputs.
- Since the Rasa actions server communicates with the Rasa (Core) main server itself through REST, there could be something wrong. Are you using the correct version of the Rasa SDK compatible with the Rasa Stack of the main bot?
- In your code, the is a `print` statement not immediately followed by parenthesis but a space character.
