### ISSUE TITLE
please update aws version with rasa merged part of chatroom

### ISSUE THREAD

**Issue by rasaworkshop** [scalableminds/chatroom#143]

**Comment by rasaworkshop** [comment]
this might fix handoff issues

**Comment by melindaloubser1** [comment]
@rasaworkshop The handoff for the rasa demo bots is dependent on the **forked** version of chatroom here:  https://github.com/RasaHQ/chatroom. The fork has not been merged into this upstream. Since it is for demo purposes, I would not recommend using the fork as-is for a production chatbot in any case.

**Comment by hotzenklotz** [comment]
Melinda is right. Closing.
