### ISSUE TITLE
changing the style of the widget

### ISSUE THREAD

**Issue by nailon** [scalableminds/chatroom#155]
Hello,
I love the chatroom widget and I use it with my Rasa X backend. 
However, I would like to change the css properties of the elements.  Is there an easy way to do this, without actually making a copy of the project and serving the js myself?  Can I pass css options to the constructor?  
Thanks :-)
Nir

**Comment by hotzenklotz** [comment]
Yes and no. Since all elements on a website life in the same namespace, you can serve your custom CSS overriding some of the CSS classes of the widget. I guess that is not really clean, but works. 

The cleaner version, is to include the widget in your project, change the SASS variables and serve it yourself.

**Comment by nailon** [comment]
thank you!  I will try these solutions out :-)
