### ISSUE TITLE
[Question] Enhanced Rasa Responses

### ISSUE THREAD

**Issue by CDFO** [scalableminds/chatroom#75]
Hi,

What will be the best option to achieve following, please?

1) Pass logged in user details to Rasa, so that it an respond with the name, something like "Hello Mike"
2) Pass HTML tags in response and format the text displayed, something like "Hello <b>Mike</b>"

Any help would be greatly appreciated.

**Comment by hotzenklotz** [comment]
@CDFO Both operations are not trivial:

### Regarding 1.
Unfortunately there is no good way to store any information from a Rasa channel in a slot. You need access to the `tracker` which a Rasa Channel does not have. 
We worked around that by passing the `agent` to our channel implementation, which is highly hacky. (See [here](https://github.com/scalableminds/chatroom/blob/master/rasa_utils/bot_server_channel.py#L155)) At one point we already supported passing a username (argument is called `display_name`) to Rasa. 

In order to get this to work, you roughly need to do this:
1. Start your bot and chatroom as described in the [advanced usage](https://github.com/scalableminds/chatroom/blob/master/README.md#advanced-usage-with-a-custom-rasa-core-project-as-custom-channel-from-python) using Python code. Make sure to pass your `agent` to the chatroom.
2. Add a new slot `username` (or similar) to you bot's config
3. Modify the `bot_server_channel.py` to handle the new `username argument` and save it to a slot. (see above) (you could also add a new route for that)
4. Make sure to trigger a custom REST request to `http://<host:port>/conversations/<cid>/say?username=Mike` in your website's Javascript that includes your the actually `username` argument as a GET argument . 

### Regarding 2. 
We support the Markdown syntax. If **bold** text is all you need then use Markdown in your text response. e.g. `Hello **Mike**` 
More complex support for further HTML tags (e.g. dropdowns etc) would require to extend the communication protocol between the chatroom and the Rasa channel.
