### ISSUE TITLE
Display intents as button after the welcome message

### ISSUE THREAD

**Issue by rageshpillai** [scalableminds/chatroom#90]
Is there any way to display all intents as button after the welcome message  text

**Comment by hotzenklotz** [comment]
Sure. Just make sure that you Rasa Core backend sends a summary of intents as button. Alternatively, integrate them in the welcome message.

**Comment by rageshpillai** [comment]
how. can you pls help me on  this

**Comment by eleow** [comment]
This is more a question on rasa-core backend rather than for this widget.

You could define it in the domain.yml under templates
eg 
utter_listIntents:
- text: "Here's the list of intents"
 buttons:
 - title: "intentA"
   payload: "/intentA{}"
- title: "intentB"
  payload: "/intentB{}"

etc

Though if you have a big list of intents or if your intents might be changing, you might want to define it in your custom actions, and programmatically generate the array of buttons for the dispatcher.utter_button_message
